version: 1

# backend:
#   name: git-gateway
#   branch: main

backend:
  name: github
  repo: v-jamparo/one-click-hugo-cms # Path to your GitHub repository
  # optional, defaults to master
  branch: main

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          update_type: security
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
    version_requirement_updates: widen_ranges